cert-manager:
  tolerations:
  - key: CriticalAddonsOnly
    operator: Exists
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: system
            operator: In
            values:
            - "true"
  cainjector:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: system
              operator: In
              values:
              - "true"
  webhook:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: system
              operator: In
              values:
              - "true"
  startupapicheck:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: system
              operator: In
              values:
              - "true"
origin-ca-issuer:
  controller:
    tolerations:
    - key: CriticalAddonsOnly
      operator: Exists
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: system
              operator: In
              values:
              - "true"
